### ISSUE TITLE
rpc on websocket don't work

### ISSUE THREAD

**Issue by Zhairgling** [heroiclabs/nakama-dart#74] opened 2023-09-14 16:42 UTC
**Describe the bug**
when I make a rpc call using websocket, I can see in the server log that I have the request and the nswer is sent but the flutter app never receive it.

**Reproduction Code**
Note: This is mandatory! If your issue does not contain it, it will be closed.

Example:
```dart

    final result1 = await socketClient.rpc(id: 'hello_world_rpc');


    print(result1.payload); // Devrait afficher "Hello, World!"

```
```ts

const helloWorldRpc: nkruntime.RpcFunction = function (ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string): string {
  return "Hello, World!";
}
```

**Expected behavior**
see "hello world " in the flutter debugconsole

**Comment by obrunsmann** [comment] 2023-09-23 06:52
Thank you @Zhairgling  for reporting. I am just back from vacation and checking in your issue shortly.

**Comment by CodingTrip93** [comment] 2024-01-20 21:36
Any update on this issue!?

**Comment by eunjijeon11** [comment] 2024-02-16 01:20
Is there any update?

**Comment by ilmalte** [comment] 2024-02-20 22:12
Bump

**Comment by ilmalte** [comment] 2024-10-22 10:46
This issue has been reported in an older version than the latest available on pub.dev, (1.1.0 released on the Mar 21).

Also, many improvements and bug fixes have been pushed to `main` since the version 1.1.0, and they will be released soon.
You might want to try to update your `pubspec.yaml` file to point directly to `main` for now:

```
dependencies:
  nakama:
    git:
      url: 'https://github.com/heroiclabs/nakama-dart.git'
      path: nakama
```

I am not certain if this will resolve the issue, so I will attempt to reproduce it and see if it needs further investigation.

**Comment by rephlex187** [comment] 2024-11-03 18:48
Just ran into the same bug (1.1.0 from pub.dev). I'll try it tomorrow with the main branch and report back/eventually fix it.

**Comment by rephlex187** [comment] 2024-11-04 04:41
Same behavior on the main branch, I'll dive into it.

**Comment by rephlex187** [comment] 2024-11-04 06:10
Might refactor this library a bit in the near future to make use of some generics, but that PR should do for now.

**Closed** 2024-12-14 10:50 UTC
Labels: type: bug
