### ISSUE TITLE
gRPC Error (code: 5, codeName: NOT_FOUND, message: RPC function not found, details: [], rawResponse: null, trailers: {})

### ISSUE THREAD

**Issue by zhangyc** [heroiclabs/nakama-dart#86] opened 2024-01-09 11:12 UTC
**Describe the bug**
When I use final response = await client.rpc(
       session: userSession!,
       id: targetId,
       payload: jsonEncode(payload),
     ); when sending a message
response：
gRPC Error (code: 5, codeName: NOT_FOUND, message: RPC function not found, details: [], rawResponse: null, trailers: {})
**Reproduction Code**
Note: This is mandatory! If your issue does not contain it, it will be closed.

Example:
```dart
When I use final response = await client.rpc(
       session: userSession!,
       id: targetId,
       payload: jsonEncode(payload),
     ); when sending a message
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1.1 23B81 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
[✓] VS Code (version 1.85.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

**pubspec.yaml**

```yaml
nakama: ^1.0.5
```

**Additional context**

**Comment by ilmalte** [comment] 2024-10-22 10:48
This issue has been reported in an older version than the latest available on pub.dev, (1.1.0 released on the Mar 21).

Also, many improvements and bug fixes have been pushed to main since the version 1.1.0, and they will be released soon.
You might want to try to update your pubspec.yaml file to point directly to main for now:

dependencies:
  nakama:
    git:
      url: 'https://github.com/heroiclabs/nakama-dart.git'
      path: nakama
I am not certain if this will resolve the issue, so I will attempt to reproduce it and see if it needs further investigation.

**Comment by ilmalte** [comment] 2024-12-17 11:18
I'll close this issue as version v1.2.0 has been published, which should resolve it. If the problem persists, please feel free to reopen the issue with additional context. Thank you!

**Closed by ilmalte** 2024-12-17 11:18 UTC
Labels: type: bug, status: needs information
